spring.application.name=order-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/order_management_db
spring.datasource.username=root
spring.datasource.password=GOPALTIROLE@111
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name = gopu
spring.security.user.password= Gopal@123
spring.security.user.roles=ADMIN
